version: "3.9" # optional since v1.27.0
services:
  integration:
    image: golang:1.18
    command: bash -c "cd /workspace && go install gotest.tools/gotestsum@latest && gotestsum -- -coverprofile=coverage.txt -timeout=10s -v -count=1 -coverpkg=./... -covermode=atomic ./..."
    volumes:
      - type: bind
        source: .
        target: /workspace
    environment:
      - DATABASE_CONNECTION_STRING=postgresql://postgres:mysecretpassword@postgres/development?connect_timeout=10
    depends_on:
      - postgres
    links:
      - postgres
  postgres:
    image: postgres
    environment:
      - POSTGRES_DB=development
      - POSTGRES_PASSWORD=mysecretpassword
